Bash script that transfers a file from our client to a server

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -5,8 +5,14 @@ if [ "$#" -ne 4 ]; then
         exit 1
 fi
 
-if [ "$#" -lt 4 ]; then
-	scp -o StrictHostKeyChecking=no "$1" "$3@$2":~/
+file_path="$1"
+server_ip="$2"
+username="$3"
+ssh_key="$4"
+
+if scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username@$server_ip:~/"; then
+        echo "$file_path transferred successfully."
 else
-	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":~/
+        echo "File transfer failed."
+        exit 1
 fi
